### PR TITLE
feat(@formatjs/cli-lib)!: convert to ESM only

### LINKED ISSUE #4764: @formatjs/cli-lib version 7.0.0 is broken
```
Error [ERR_MODULE_NOT_FOUND]: 
   Cannot find module '/home/user/project/node_modules/@formatjs/cli-lib/lib_esnext/src/extract' 
   imported from /home/user/project/node_modules/@formatjs/cli-lib/lib_esnext/index.js
```

The package `@formatjs/cli-lib` as of version 7.0.0 is an EcmaScript module because of the following configuration in `package.json`:

```
 "type": "module",
```

However, the mandatory `.js` extensions are missing from the imported files. The package uses CommonJS naming convention where file extensions are optional in the `require`d modules.

### LINKED ISSUE #5152: @formatjs/cli-lib does not have a valid entry-point
[`packages/cli-lib/package.json`](https://github.com/formatjs/formatjs/blob/main/packages/cli-lib/package.json#L52) only exposes `main` entry-point that points to `packages/cli-lib/index.js`.

`index.js` [does not exists in built package ](https://www.npmjs.com/package/@formatjs/cli-lib?activeTab=code) because all the built sources are placed in `packages/cli-lib/lib_esnext`.

This renders the package (as of 7.4.4) useless as no bundler can resolve `main` section of the `@formatjs/cli-lib` package.

Introduced in https://github.com/formatjs/formatjs/commit/acdda0c1d4f5bfbdac8afd5c0a308fb36a29b589, proposed fix https://github.com/formatjs/formatjs/pull/4979

### PR DESCRIPTION
**Pull request by longlho**
### TL;DR

Convert `cli-lib` package to use ES modules by adding `.js` extensions to imports and setting `"type": "module"` in package.json.  
  
Fix #5152

Fix #4764

### What changed?

- Added `"type": "module"` to package.json to enable ES modules
- Updated all import statements to include `.js` file extensions
- Converted CommonJS require syntax to ES module imports in main.ts
- Fixed chalk import to handle both default and named exports
- Disabled the `subject-exclamation-mark` rule in commitlint config

### How to test?

1. Run the CLI tool to ensure it works with the new module format
2. Test extract and compile functionality to verify imports are working correctly
3. Verify that the package can be imported properly in both CommonJS and ESM projects

### Why make this change?

This change modernizes the codebase to use ES modules, which is the standard module system for JavaScript. Using explicit file extensions in imports improves compatibility with ES modules and makes the import resolution more predictable. This change also aligns with Node.js best practices for package structure.

### CODE REVIEW

**Comment by longlho** [comment]
* **#5211** <a href="https://app.graphite.com/github/pr/formatjs/formatjs/5211?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#5208** <a href="https://app.graphite.com/github/pr/formatjs/formatjs/5208?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#5207** <a href="https://app.graphite.com/github/pr/formatjs/formatjs/5207?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#5204** <a href="https://app.graphite.com/github/pr/formatjs/formatjs/5204?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/formatjs/formatjs/5204?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add either label to this PR to merge it via the merge queue:
- <kbd>main</kbd> - adds this PR to the back of the merge queue
- <kbd>hotfix</kbd> - for urgent hot fixes, skip the queue and merge this PR next

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.com/invite/github/formatjs?ref=merge-queue-instructions-in-stack-comment&prId=5204).

<h2></h2>
<sub>

An organization admin has required the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
