### ISSUE TITLE
@formatjs/cli-lib version 7.0.0 is broken

### ISSUE THREAD

**Issue by aradzie** [formatjs/formatjs#4764]
```
Error [ERR_MODULE_NOT_FOUND]: 
   Cannot find module '/home/user/project/node_modules/@formatjs/cli-lib/lib_esnext/src/extract' 
   imported from /home/user/project/node_modules/@formatjs/cli-lib/lib_esnext/index.js
```

The package `@formatjs/cli-lib` as of version 7.0.0 is an EcmaScript module because of the following configuration in `package.json`:

```
 "type": "module",
```

However, the mandatory `.js` extensions are missing from the imported files. The package uses CommonJS naming convention where file extensions are optional in the `require`d modules.

**Comment by aradzie** [comment]
We suggest to configure the [`eslint-plugin-n`](https://github.com/eslint-community/eslint-plugin-n) ESLint plugin with the [`n/file-extension-in-import`](https://github.com/eslint-community/eslint-plugin-n/blob/master/docs/rules/file-extension-in-import.md) rule to fix the missing extensions. 

The rule is fixable so all the missing `.js` extensions in the imported modules can be automatically appended by running `eslint --fix`.

**Comment by longlho** [comment]
apology for breaking this. Any reason you're not using the CLI?

**Comment by izorg** [comment]
> Any reason you're not using the CLI?

We have a custom integration. We extract keys by entrypoints by building dependency tree. So we are using Node API in our script instead of multiple command calls

**Comment by NullVoxPopuli** [comment]
I just ran in to this as well. Since my custom CLI tool is small, I set `type: module` in package.json -- however, this did not fix the issue.

The error is about `lib_esnext/src/extract` but the file is `lib_esnext/src/extract.js` in ESM... the extensions need to exist.

Things that need to be fixed:
- all imports must have extensions
- folders can't be imported anymore, so for example, when importing `./formatters`, you need to import instead `./formatters/index.js`
- `import { hoistSelectors } from '@formatjs/icu-messageformat-parser/manipulator';` won't work without a package.json#exports config aliasing `./manipulator` to `./manipulator.js` -- which you can do via:
  ```js
  "exports": {
    ".": "lib/index.js",
    "./*: "lib/*.js"
  }
  ```
  - this library has the same problem as the CLI-lib, there are no extensions on the relative imports

Even after fixing the above locally, I get this error:
```js
ref_km24djpfvefothdey2goejyaoe/node_modules/@formatjs/cli-lib/lib_esnext/src/console_utils.js:1
import { green, red, supportsColor, yellow } from 'chalk';
         ^^^^^
SyntaxError: Named export 'green' not found. The requested module 'chalk' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'chalk';
const { green, red, supportsColor, yellow } = pkg;
```


So, thankfully the error says how to move forward.
Alternatively, cli-lib could upgrade chalk, which is esm-only.

Same for fs-extra:
```js
ref_vvl6jp6wpkowtgjpi5rqqcbici/node_modules/@formatjs/cli-lib/lib_esnext/src/compile.js:2
import { outputFile, readJSON } from 'fs-extra';
                     ^^^^^^^^
SyntaxError: Named export 'readJSON' not found. The requested module 'fs-extra' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'fs-extra';
const { outputFile, readJSON } = pkg;
```

(and since I'm upgrading from v6):
```js
import CLI from '@formatjs/cli-lib';
       ^^^
SyntaxError: The requested module '@formatjs/cli-lib' does not provide an export named 'default'
```


so, this actually needs to be either:
```js
import * as CLI from '@formatjs/cli-lib';

CLI.extractAndWrite(...)
```
or
```js
import { extractAndWrite } from '@formatjs/cli-lib';
```
(my preference)

but then!!
Another error:
```js
Error [ERR_REQUIRE_CYCLE_MODULE]: 
  Cannot require() ES Module <.pnpm>/@formatjs+icu-messageformat-parser@2.9.7_patch_hash=pf5m2fqbj2gtwat25phxiuf5ty/node_modules/@formatjs/icu-messageformat-parser/lib/index.js 
  in a cycle. 
  (from <.pnpm>/@formatjs+ts-transformer@3.13.26/node_modules/@formatjs/ts-transformer/src/transform.js)
```
so it seems `@formatjs/ts-transformer` _also_ has all the same problems as the other packages -- it needs a package.json#exports to target ESM/require differences

**Comment by NullVoxPopuli** [comment]
For others, here is how you can move forward with v7 before they fix the builds if you need the features / fixes (like I did):

- use pnpm (or a modern npm / yarn 4+ / some other modern package manager)
- copy the attached patches to your patches directory
- set this config (or similar for your package manager)
  ```js
  "pnpm": {
    "patchedDependencies": {
      "@formatjs/cli-lib": "patches/@formatjs__cli-lib.patch",
      "@formatjs/icu-messageformat-parser@2.9.7": "patches/@formatjs__icu-messageformat-parser@2.9.7.patch",
      "@formatjs/ts-transformer@3.13.26": "patches/@formatjs__ts-transformer@3.13.26.patch"
    }
  }
  ```

[@formatjs__ts-transformer@3.13.26.patch](https://github.com/user-attachments/files/18100821/%40formatjs__ts-transformer%403.13.26.patch)
[@formatjs__icu-messageformat-parser@2.9.7.patch](https://github.com/user-attachments/files/18100823/%40formatjs__icu-messageformat-parser%402.9.7.patch)
[@formatjs__cli-lib.patch](https://github.com/user-attachments/files/18100826/%40formatjs__cli-lib.patch)

**Comment by aradzie** [comment]
> apology for breaking this. Any reason you're not using the CLI?

I have build a custom workflow around the tools of formatjs. I have a script that:

1. Scans multiple packages in a monorepo for translations.
2. Synchronizes translations in different languages, keeps translation ids sorted, etc.
3. Writes translations report.

To be honest, I wrote the script long time ago, and don't remember exactly, but I think it is impossible to achieve the same goals with just bare CLI tools.

**Comment by NullVoxPopuli** [comment]
Not impossible. We have the same use case <3

**Comment by longlho** [comment]
Thanks for the patience while I sort out this esm interop mess. Prob won't have time till EOW.
The CLI supports vue which seems to go all in on esm while others still provide cjs which choked when we tried to upgrade it.

**Comment by krulis-martin** [comment]
I think the problem with "SyntaxError: Named export 'green' not found. The requested module 'chalk'" error might be fixed by switching to chalk 5.x (if I checked correctly v4 is CJS, but v5 switched to ESM which should do the trick).

**Comment by nstepien** [comment]
Not stale!

**Comment by bryansantamaria** [comment]
This is still not fixed, any updates on when you will have time to address this @longlho? 🙏

**Comment by SergeyKrasnolobov** [comment]
@longlho Also is waiting for this fix as soon as possible!!!

**Comment by TylerK** [comment]
Same, building a NX executor to extract strings and would love to use the Node API instead of exec-ing the CLI :)

**Comment by longlho** [comment]
sry will try to find some time this week/end

**Comment by NullVoxPopuli** [comment]
looks like this issue is still present on 7.3.3. these files need extensions:
```
node_modules/@formatjs/cli-lib/lib_esnext/index.js
```

**Comment by longlho** [comment]
can you guys try latest version?

**Comment by walkerburgin** [comment]
`7.3.4` fails for me with an error like this: 

```
> formatjs-esm-repro@ test /Users/wburgin/Repositories/walkerburgin/formatjs-esm-repro
> ./test.mjs example.jsx

node:internal/modules/esm/resolve:188
  const resolvedOption = FSLegacyMainResolve(packageJsonUrlString, packageConfig.main, baseStringified);
                         ^

Error: Cannot find package '/Users/wburgin/Repositories/walkerburgin/formatjs-esm-repro/node_modules/@formatjs/cli-lib/package.json' imported from /Users/wburgin/Repositories/walkerburgin/formatjs-esm-repro/test.mjs
    at legacyMainResolve (node:internal/modules/esm/resolve:188:26)
    at packageResolve (node:internal/modules/esm/resolve:769:14)
    at moduleResolve (node:internal/modules/esm/resolve:831:20)
    at defaultResolve (node:internal/modules/esm/resolve:1036:11)
    at DefaultModuleLoader.resolve (node:internal/modules/esm/loader:251:12)
    at DefaultModuleLoader.getModuleJob (node:internal/modules/esm/loader:140:32)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:33)
    at link (node:internal/modules/esm/module_job:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v20.5.1
 ELIFECYCLE  Test failed. See above for more details.
```

It looks like `package.json` points to a `main` (`index.js`) that doesn't exist: 

```
➜  formatjs-esm-repro git:(master) ls node_modules/@formatjs/cli-lib/
LICENSE.md   README.md    lib_esnext   node_modules package.json
```

It also looks like relative imports in the `lib_esnext` directory are still missing extensions as well.

Small standalone repro here if it's helpful: https://github.com/walkerburgin/formatjs-esm-repro

**Comment by longlho** [comment]
Latest version doesn't support esm

**Comment by SergeyKrasnolobov** [comment]
> Latest version doesn't support esm

Why?

**Comment by dustinlessard-wf** [comment]
> Why?

That's a really good question.  Our engineers are wondering this exact thing.  It caused us some headaches and if there's a good reason, that may make it worth the headaches.

**Comment by longlho** [comment]
We basically have to convert downstream packages to esm and that's a lot of breaking changes. Supporting both is even worse.

**Comment by avasuro** [comment]
In version 7.4.1, the following import does not work for me at all:
```ts
import { extract } from '@formatjs/cli-lib'
```

This is because there's no index.js file in the package root, even though the package.json of @formatjs/cli-lib declares it as the main entry point:
```js
// node_modules/@formatjs/cli-lib/package.json
{
  ...
  "main": "index.js",
}
```

Temporary fixed by direct import from @formatjs/cli-lib/lib_esnext:
```ts
import { extract } from '@formatjs/cli-lib/lib_esnext'
```

**Comment by septs** [comment]
Currently, the API Expose of this library is not suitable for third-party integration development.

The webpack loader integration [^1] I am doing now copies some logic from this library. If I make another webpack plugin to do automatic extract messages, I will also need to copy some code

If more APIs can be exposed instead of this file-based API design, I believe there will be a **better developer experience**.

for example: develop a webpack plugin on rebuild than automatic re-generate extracted message file.

[^1]: https://github.com/NiceLabs/formatjs-webpack-loader

**Comment by a-ivanov81** [comment]
> In version 7.4.1, the following import does not work for me at all:
> 
> import { extract } from '@formatjs/cli-lib'
> This is because there's no index.js file in the package root, even though the package.json of @formatjs/cli-lib declares it as the main entry point:
> 
> // node_modules/@formatjs/cli-lib/package.json
> {
>   ...
>   "main": "index.js",
> }
> Temporary fixed by direct import from @formatjs/cli-lib/lib_esnext:
> 
> import { extract } from '@formatjs/cli-lib/lib_esnext'

`import { extract } from '@formatjs/cli-lib/lib_esnext'`

Not work in 7.4.2

```
Error: Directory import '...\apps\web\node_modules\@formatjs\cli-lib\lib_esnext' is not supported resolving ES modules imported from ...\apps\web\intl\extract.ts
Did you mean to import "@formatjs/cli-lib/lib_esnext/index.js"?
    at finalizeResolution (node:internal/modules/esm/resolve:262:11)
    at moduleResolve (node:internal/modules/esm/resolve:859:10)
    at defaultResolve (node:internal/modules/esm/resolve:983:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:801:12)
    at ModuleLoader.#cachedDefaultResolve (node:internal/modules/esm/loader:725:25)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:708:38)
    at ModuleLoader.getModuleJobForImport (node:internal/modules/esm/loader:309:38)
    at ModuleJob.#link (node:internal/modules/esm/module_job:202:49) {
  code: 'ERR_UNSUPPORTED_DIR_IMPORT',
  url: 'file:///.../apps/web/node_modules/@formatjs/cli-lib/lib_esnext'
}
```

for `import { extract } from '@formatjs/cli-lib/lib_esnext/index.js'`

```
Error: Cannot find module ...\node_modules\.pnpm\@formatjs+cli-lib@7.4.2_@vue+compiler-core@3.5.18\node_modules\@formatjs\cli-lib\lib_esnext\src\extract' imported from ...\node_modules\.pnpm\@formatjs+cli-lib@7.4.2_@vue+compiler-core@3.5.18\node_modules\@formatjs\cli-lib\lib_esnext\index.js
    at finalizeResolution (node:internal/modules/esm/resolve:274:11)
    at moduleResolve (node:internal/modules/esm/resolve:859:10)
    at defaultResolve (node:internal/modules/esm/resolve:983:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:801:12)
    at ModuleLoader.#cachedDefaultResolve (node:internal/modules/esm/loader:725:25)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:708:38)
    at ModuleLoader.getModuleJobForImport (node:internal/modules/esm/loader:309:38)
    at ModuleJob.#link (node:internal/modules/esm/module_job:202:49) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///.../node_modules/.pnpm/@formatjs+cli-lib@7.4.2_@vue+compiler-core@3.5.18/node_modules/@formatjs/cli-lib/lib_esnext/src/extract'
}
```

**Comment by NullVoxPopuli** [comment]
someone still needs to go through all the imports and add extensions

**Comment by TheTempest7** [comment]
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '...\node_modules\@formatjs\cli-lib\lib_esnext\src\extract' imported from ...\app\node_modules\@formatjs\cli-lib\lib_esnext\index.js
    at finalizeResolution (node:internal/modules/esm/resolve:274:11)
    at moduleResolve (node:internal/modules/esm/resolve:864:10)
    at defaultResolve (node:internal/modules/esm/resolve:990:11)
    at #cachedDefaultResolve (node:internal/modules/esm/loader:768:20)
    at #resolveAndMaybeBlockOnLoaderThread (node:internal/modules/esm/loader:804:38)
    at ModuleLoader.resolveSync (node:internal/modules/esm/loader:827:52)
    at #cachedResolveSync (node:internal/modules/esm/loader:787:25)
    at ModuleLoader.getModuleJobForRequire (node:internal/modules/esm/loader:474:50)
    at #link (node:internal/modules/esm/module_job:441:34)
    at new ModuleJobSync (node:internal/modules/esm/module_job:414:17) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///.../node_modules/@formatjs/cli-lib/lib_esnext/src/extract'
Node.js v24.8.0

i`ve tried 7.0.0 and 7.4.2 - same result
compile function imported well but extract do not 
adding lib_esnext\index.js to import do not help at all 
the error apears when i run custom extract script (on 6 version run properly)
also i using CommonJS
do 7 version support CommonJS?
is migration guide from 6 to 7 comming?
