### ISSUE TITLE
Support for gsw-CH in the @formatjs/intl-numberformat polyfill

### ISSUE THREAD

**Issue by AnjaRoseBikes** [formatjs/formatjs#4520]
## Which package?

@formatjs/intl-numberformat
@formatjs/intl-numberformat/locale-data/gsw-ch

Google Chrome Version 128.0.6613.120 

## Describe the bug

The `gsw-CH` (Swiss German - Switzerland) locale is not currently supported in the `@formatjs/intl-numberformat` polyfill. This locale is commonly used in Switzerland for the Swiss German dialect and is important for correctly formatting numbers and currency according to local conventions. The absence of this locale creates issues for developers needing specific regional number and currency formatting.

### Reproducible Steps/Repo
1. Attempt to format a number using `Intl.NumberFormat('gsw-CH')` with the `@formatjs/intl-numberformat` polyfill.
2. Notice that "Cannot find module '@formatjs/intl-numberformat/locale-data/gsw-ch' or its corresponding type declarations."
3. Using `Intl.NumberFormat('gsw')` or `Intl.NumberFormat('de-CH')` does not lead to the desired result

```
new Intl.NumberFormat('gsw-CH', {
  style: 'currency',
  currency: 'CHF',
}).format(23900.12);
// This results in an unsupported locale error.
```

## Expected behavior

Support for the `gsw-CH` locale should be added to the polyfill, allowing proper formatting of Swiss German numbers and currency, e.g.,:
```
new Intl.NumberFormat('gsw-CH', {
  style: 'currency',
  currency: 'CHF',
}).format(23900.12);
// Expected output: "23’900.12 CHF
```

## Screenshots

Working in Firefox 130.0 
![image](https://github.com/user-attachments/assets/82601624-94f4-4d48-bd97-00da26eaeed7)

Not working in Google Chrome Version 128.0.6613.120 
![image](https://github.com/user-attachments/assets/f5d188bc-2de7-40d5-827a-f49870f5b8c8)

## Additional context

The `gsw-CH` locale is important for applications targeting the Swiss market, where Swiss German is widely spoken. Adding support for this locale will help developers provide a better user experience by displaying correctly formatted numbers and currency.

**Comment by longlho** [comment]
Our data comes from CLDR so if it’s not there then you should check CLDR

**Comment by AnjaRoseBikes** [comment]
Thank you, I will check!
