### ISSUE TITLE
Type error on FormattedMessage values prop with rich text formatting value

### ISSUE THREAD

**Issue by wouter-leistra** [formatjs/formatjs#3550]
## Which package?
react-intl 5.25.0

## Describe the bug
FormattedMessage values expect Record<string, ReactNode> but documentation for rich text expects a function (https://formatjs.io/docs/react-intl/components/#rich-text-formatting). Resulting in a type error.

## Expected behavior
Type should be corrected or documentation should be updated on how to do rich text on FormattedMessage component.

## Additional context
react 18 was used in the project when the type error occurred.
react-intl 5.22.0 has not given any issues previously.

**Comment by m-rutter** [comment]
Here is a [typescript playground reproduction of this problem](
https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AoUSWOAbzgDFoQUYYkATAWSQGdeUAcyRwAvnGy4CRdDAC0wAHYwANmXLkAPEygs2nHvyFJycOMA4BeAESYIEa6bgckmFAFcVMQwOE2AKhBwAEbuAJ5wKHC8ABYQSAA0cJooAHwAbsC8wPAQ7lBwAO5IwdnsmgD0aZGKHMkYaaERUbHxlQ2pjmbpKCrufJa0tE5mKABccGgx7ooA1rxwlqlwABQjZsko6xuTKij8NkgAHuxQir0A+ipKs107GzAoUMIwNhfBe3N393AxRJg2GJsMC8MYVCqFSEAOmOKHAKiQULQuAqrSQ3w2qW2G1oUxm81E2MqaXWAEoEusGhM8XMFktkrwYDhFIJdvteDYqNBHsprKlcdNaaJKozmYJUhSzKJCRVUkA):

This is almost certainly related to the breaking change here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56210

The values prop has the type `Record<string, ReactNode>`. `ReactNode` prior to 18.0.0 included the type `{}`, which is effectively `unknown` minus `null` and `undefined`. This meant that in practice `ReactNode` accepted any value including `null` and `undefined` because they are also part of that union. This was quite unsafe.

The type `{}` has been removed from the union `ReactNode`, and so the value being a funtion is now a type error. The the value prop needs to be updated to accept a union that looks roughly like this:

```ts
type Values = Record<string, ReactNode | ((chunks: string[]) => JSX.Element) | Date>
```

**Comment by nstepien** [comment]
Having the same issue but with `Date`s instead, for example
```tsx
  return (
    <FormattedMessage
      id="now"
      defaultMessage="Now: {now, date, medium}"
      values={{ now: new Date() }}
    />
  );
```
```
src/... - error TS2322: Type 'Date' is not assignable to type 'ReactNode'.

6   values={{ now: new Date() }}
              ~~~

```

**Comment by ar7casper** [comment]
Hi,

This bug is due to the fact that some packages made the upgrade to react 18 and some haven't, so you get issues with types.
The solution is quite simple - 
```
"resolutions": {
    "@types/react": "<18.0.0",
    "@types/react-dom": "<18.0.0"
  },
  ``` 
  In case you use `yarn`.
  
  If you use `npm`, you can follow - https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides

**Comment by longlho** [comment]
Thanks for reporting! We'll take a look asap.

**Comment by nstepien** [comment]
Not stale at all.

**Comment by gavrichards** [comment]
`5.25.0` broke plural strings on Android for me. Rolling back to `5.24.8` fixes it. Presume it must be related.

**Comment by StampixSMO** [comment]
Any update on this?

**Comment by peetjvv** [comment]
@StampixSMO , from [this comment](https://github.com/formatjs/formatjs/issues/3593#issuecomment-1131836876) looks like a fix was released around May. Can confirm it's fixed for me when upgrading `react-intl` from v5 to v6 with `react v18.2.0` and `@types/react v18.0.26`
