### ISSUE TITLE
"formatter.formatHTMLMessage is not a function" in console error when migrate v2 to v3

### ISSUE THREAD

**Issue by toy9986619** [formatjs/formatjs#2783]
## Which package?
react-intl v3.12.1

## Describe the bug
I use react-intl v2 (2.7.2) in my project, and I found it may have some bug when change locale and message with legacy context.
IntlProvider change the props, but context not change the messages. (with #1097 )
So I try upgrade version and upgrade it one version at one time.

When I migrate react-intl v2 (2.7.2) to v3 (3.12.1), I get [React Intl] error in browser console.
It shows

```
[React Intl] Error formatting message: "auth.login" for locale: "zh-hant"
TypeError: formatter.formatHTMLMessage is not a function
```

and 

```
[React Intl] Cannot format message: "auth.login", using message source as fallback.
```

## To Reproduce

I tried it on codesandbox, but I didn't see any error in console, so I cannot reproduce it...
I am in the working time now, I will provide the repository soon.

codesandbox URL: https://codesandbox.io/s/gifted-goodall-zktz3

## Expected behavior
react-intl can format the string success without warning

## Screenshots

![image](https://user-images.githubusercontent.com/19423708/113234696-5911e880-92d4-11eb-91e7-a9a329953701.png)

The error line is here:
![image](https://user-images.githubusercontent.com/19423708/113233961-f4a25980-92d2-11eb-8891-d5ec0ae082b7.png)

My testing code in project is like:
![image](https://user-images.githubusercontent.com/19423708/113234741-6cbd4f00-92d4-11eb-952a-b565feafa057.png)

![image](https://user-images.githubusercontent.com/19423708/113234716-6333e700-92d4-11eb-8f2a-ae24d32fd19f.png)

![image](https://user-images.githubusercontent.com/19423708/113234505-fae50580-92d3-11eb-8b76-45a14077102f.png)

I try to not use all project code, just these little code snippet also make the error.

## Desktop:

- OS: MacOs mojave 10.14.6
- Browser: chrome
- Version: 89.0.4389.90 (x86_64)
- React version: 16.8.6
- webpack: 4.28.4
- babel: 7.5.5

it build with webpack 4, not use with 'create-react-app'

**Comment by toy9986619** [comment]
ok... after I try to create a little repo to reproduce this bug, I found the reason that the project had a lib dependency with old 
 react-intl version (v2).
After I deleted it in package.json, this error message was not shown.
I upgrade the lib to react-intl v3, and npm link it with my project, the error message was not shown.
So I think it is the old dependency to make this error.

But I have another question with react-intl v3, I will open a new issue to ask it.
Thanks.
